# Generated by Django 5.2.3 on 2025-06-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="nombres",
            new_name="nombre",
        ),
    ]
