# Generated by Django 5.2.3 on 2025-06-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_project_id_tareas_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="tareas",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
