# Generated by Django 3.2.8 on 2025-07-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fincas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_finca', models.CharField(max_length=250)),
                ('pais_finca', models.CharField(max_length=50)),
                ('descripcion_finca', models.CharField(max_length=500)),
                ('imagen_finca', models.CharField(max_length=900)),
                ('active_finca', models.BooleanField(default=True)),
            ],
        ),
    ]
